name: Update MusicBot JAR

on:
  schedule:
    - cron: '0 5 * * *'  # Run daily at 5 AM UTC
  workflow_dispatch:  # Allow manual triggers

jobs:
  check-and-update-jar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for all tags and branches
      
      - name: Get the current repository release version
        id: current-release
        run: |
          current_version=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          current_version=${current_version#v}  # Remove 'v' prefix if present
          echo "Current release: $current_version"
          echo "::set-output name=current_version::$current_version"

      - name: Check for new MusicBot release
        id: check-release
        run: |
          latest_release=$(curl -s https://api.github.com/repos/jagrosh/MusicBot/releases/latest | jq -r .tag_name)
          echo "Latest release: $latest_release"
          echo "::set-output name=new_version::$latest_release"
     
      - name: Update JAR file
        id: update-jar
        run: |
          current_version="${{ steps.current-release.outputs.current_version }}"
          latest_version="${{ steps.check-release.outputs.new_version }}"
          
          if [ "$latest_version" != "$current_version" ]; then
            echo "New version available: $latest_version"
            mkdir -p jdiscordmusicbot
            wget https://github.com/jagrosh/MusicBot/releases/download/$latest_version/JMusicBot-$latest_version.jar -O jdiscordmusicbot/JMusicBot-$latest_version.jar
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add jdiscordmusicbot/JMusicBot-$latest_version.jar
            git commit -m "Add JMusicBot version $latest_version"
            git push
            echo "::set-output name=updated::true"
            echo "::set-output name=new_version::$latest_version"
          else
            echo "No new version available. Current version is up to date."
            echo "::set-output name=updated::false"
          fi

      - name: Update variables.tf
        if: steps.update-jar.outputs.updated == 'true'
        run: |
          sed -i 's/default     = "JMusicBot-.*\.jar"/default     = "JMusicBot-${{ steps.check-release.outputs.new_version }}.jar"/' variables.tf
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add variables.tf
          git commit -m "Update default JAR version in variables.tf"
          git push

      - name: Create Release
        if: steps.update-jar.outputs.updated == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.update-jar.outputs.new_version }}
          release_name: Release ${{ steps.update-jar.outputs.new_version }}
          body: Updated to JMusicBot version ${{ steps.check-release.outputs.new_version }}
          draft: false
          prerelease: false